notify = ["/opt/homebrew/bin/python3", "/Users/biboy/.codex/notify.py"]

model                    = "gpt-5.4"
model_verbosity          = "medium"  # low|medium|high
model_reasoning_effort   = "xhigh"
show_raw_agent_reasoning = true

exec_timeout_ms = 900000               # 15 minutes
rmcp_client     = true
web_search      = "live"

[tui    ]
spinner = { name = "brailleDotsClassic" }
notifications = true
status_line = ["model-with-reasoning", "current-dir", "context-remaining", "five-hour-limit"]

[notice]
hide_gpt5_1_migration_prompt = true
hide_rate_limit_model_nudge = true

[notice.model_migrations]
"gpt-5.2" = "gpt-5.3-codex"

[features]
streamable_shell     = true
